import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :home_ware, HomeWareWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: HomeWare.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
config :ex_aws,
  access_key_id: "DO_SPACES_ACCESS_KEY",
  secret_access_key: "DO_SPACES_SECRET_KEY",
  region: "DO_SPACES_REGION",
  s3: [
    scheme: "https://",
    host: "DO_SPACES_BUCKET.DO_SPACES_REGION.digitaloceanspaces.com",
    region: "DO_SPACES_REGION"
  ]
